Fix the cabal-fmt installation error in cabal-fmt CI job
Cabal installation in cabal project directory affects by dependencies in
.cabal file. So run it with --ignore-project option to avoid the side
effect.

```
$ Run cabal install --overwrite-policy=always -j cabal-fmt
  cabal install --overwrite-policy=always -j cabal-fmt
  shell: /usr/bin/bash -e {0}
Error: [Cabal-7107]
Could not resolve dependencies:
[__0] trying: haskellorls-0.6.1.0 (user goal)
[__1] next goal: base (dependency of haskellorls)
[__1] rejecting: base-4.16.4.0/installed-4.16.4.0 (conflict: haskellorls => base>=4.19 && <4.22)
[__1] rejecting: base; 4.21.0.0, 4.20.0.1, 4.20.0.0, 4.19.2.0, 4.19.1.0, 4.19.0.0, 4.18.2.1, 4.18.2.0, 4.18.1.0, 4.18.0.0, 4.17.2.1, 4.17.2.0, 4.17.1.0, 4.17.0.0, 4.16.4.0, 4.16.3.0, 4.16.2.0, 4.16.1.0, 4.16.0.0, 4.15.1.0, 4.15.0.0, 4.14.3.0, 4.14.2.0, 4.14.1.0, 4.14.0.0, 4.13.0.0, 4.12.0.0, 4.11.1.0, 4.11.0.0, 4.10.1.0, 4.10.0.0, 4.9.1.0, 4.9.0.0, 4.8.2.0, 4.8.1.0, 4.8.0.0, 4.7.0.2, 4.7.0.1, 4.7.0.0, 4.6.0.1, 4.6.0.0, 4.5.1.0, 4.5.0.0, 4.4.1.0, 4.4.0.0, 4.3.1.0, 4.3.0.0, 4.2.0.2, 4.2.0.1, 4.2.0.0, 4.1.0.0, 4.0.0.0, 3.0.3.2, 3.0.3.1 (constraint from non-reinstallable package requires installed instance)
[__1] fail (backjumping, conflict set: base, haskellorls)
After searching the rest of the dependency tree exhaustively, these were the goals I've had most trouble fulfilling: base, haskellorls

Error: Process completed with exit code 1.
```